sentence = { word ~ (whitespace ~ word)* ~ punctuation? }
word = { syllable+ }
syllable = { pinyin_alphabet+ ~ tone }
pinyin_alphabet = { "b" | "p" | "m" | "f" | "d" | "t" | "n" | "l" | "g" | "k" | "h" | "j" 
| "q" | "x" | "zh" | "ch" | "sh" | "r" | "z" | "c" | "s" | "y" | "w" | "a" | "o" | "e" 
| "i" | "u" | "ü" }
tone = { "1" | "2" | "3" | "4" | "5" }
whitespace = { " " }
punctuation = { "." | "!" | "?" }